spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/crazy_db
        username: alma
        password: alma
    sql:
      init:
          mode: always

jwt:
    secret: almadsadasdkas123askd22kq3231k31kdsakdkaskdsakdksakdkakkdksakdksakdkasdkaskdkaskdksakdksakdksa
    expiration: 900